---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZhouLele.
--- DateTime: 2025/10/31 22:04
---
-- 安全转换函数
local function safe_tonumber(str)
    if type(str) == "number" then
        return str
    end
    if type(str) ~= "string" then
        return nil
    end

    -- 移除非数字字符（保留负号和小数点）
    str = string.gsub(str, "[^0-9%.%-]", "")
    return tonumber(str)
end
-- 输入参数 "
local tokenKey = KEYS[1]
local resultKey = KEYS[2]
-- 解析输入参数 " 
local currentTime = safe_tonumber(ARGV[1])
local expireTime = safe_tonumber(ARGV[2])
-- 检查令牌是否存在且有效 "
local tokenValue = redis.call('GET', tokenKey)
if not tokenValue then
    return 'NOT_EXISTS'
end
-- 标记为已使用,并再次设置过期时间
redis.call('SET', tokenKey, 'USED', 'EX', expireTime)
-- 记录使用时间
redis.call('HSET', resultKey, 'used_time', currentTime)
redis.call('EXPIRE', resultKey, expireTime)
return "\"SUCCESS\""