<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!-- <parent> -->
	<!-- 	<groupId>io.github.quiethappiness</groupId> -->
	<!-- 	<artifactId>jy-wrench</artifactId> -->
	<!-- 	<version>1.0.0</version> -->
	<!-- </parent> -->
	<groupId>io.github.quiethappiness</groupId>
	<artifactId>jy-wrench-bom</artifactId>
	<version>1.3.1-SNAPSHOT</version>
	
	<packaging>pom</packaging>
	
	<name>jy-wrench-bom</name>
	<description>Bill of Materials POM (BOM) for the jy wrench modules</description>
	<url>https://gitee.com/quiethappiness/jy-wrench</url>
	
	<licenses>
		<license>
			<name>Apache License</name>
			<url>https://opensource.org/license/apache-2-0/</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<repositories>
		<repository>
			<name>Central Portal Snapshots</name>
			<id>central-portal-snapshots</id>
			<url>https://central.sonatype.com/repository/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<developers>
		<developer>
			<id>maven</id>
			<name>jingyue</name>
			<email>zhlele2003@qq.com</email>
			<url>https://github.com/quiethappiness</url>
			<organization>jy-wrench</organization>
			<organizationUrl>https://github.com/quiethappiness/jy-wrench</organizationUrl>
			<roles>
				<role>Project Manager</role>
				<role>Developer</role>
			</roles>
			<timezone>Asia/Shanghai</timezone>
		</developer>
	</developers>
	
	<scm>
		<connection>scm:git:https://github.com/quiethappiness/jy-wrench.git</connection>
		<developerConnection>scm:git:https://github.com/quiethappiness/jy-wrench.git</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/quiethappiness/jy-wrench</url>
	</scm>
	
	<dependencyManagement>
		<dependencies>
			
			<!-- jy wrench dcc 动态配置中心 -->
			
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-dynamic-config-center</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench design framework  -->
			<!-- 一般用在domain 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-design-framework</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench traffic control -->
			<!-- 一般用在trigger 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-traffic-control</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench task job -->
			<!-- 一般用在domain 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-task-job</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench lua manager -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-lua-manager</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench infrastructure util -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-infrastructure-starter</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench method extention -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-method-extention</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench db router -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-db-router</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench aop util -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-aop</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			<!-- jy wrench redisson util -->
			<!-- 一般在infrastucture + trigger 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-redisson-starter</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			<!-- jy wrench mq message util -->
			<!-- 一般用在domain 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-mq-message-starter</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench mq listener util -->
			<!-- 一般用在trigger 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-mq-listener-starter</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			
			<!-- jy wrench threadpool manager -->
			<!-- 一般用在app 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-starter-threadpool-manager</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			<!-- jy wrench util task -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-task</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			<!-- jy wrench util mq publisher -->
			<!-- 一般用在infrastructure 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-mq-publisher</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			<!-- jy wrench web util  -->
			<!-- 一般用在app 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-web-config-starter</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
			<!-- jy wrench util types common  -->
			<!-- 一般用在types 层使用  -->
			<dependency>
				<groupId>io.github.quiethappiness</groupId>
				<artifactId>jy-wrench-util-types-common</artifactId>
				<version>1.3.1-SNAPSHOT</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<resources>
						<resource>
							<directory>src/main/resources</directory>
							<filtering>false</filtering>
						</resource>
					</resources>
				</configuration>
			</plugin>
			
			<!--   central发布插件    -->
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
				<version>0.8.0</version>
				<extensions>true</extensions>
				<configuration>
					<publishingServerId>ossrh</publishingServerId>
					<!-- <tokenAuth>true</tokenAuth> -->
					<autoPublish>true</autoPublish>
					<waitUntil>published</waitUntil>
				</configuration>
			</plugin>
			
			<!--   source源码插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.2.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<!--   javadoc插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.9.1</version>
				<configuration>
					<charset>UTF-8</charset>
					<encoding>UTF-8</encoding>
					<docencoding>UTF-8</docencoding>
					<additionalJOption>-Xdoclint:none</additionalJOption>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<additionalparam>-Xdoclint:none</additionalparam>
							<!--  /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/bin/javadoc -->
							<javadocExecutable>
								${java.home}${file.separator}bin${file.separator}javadoc
							</javadocExecutable>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<!--gpg加密-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<!--指定用于签名的 GPG 密钥名称。-->
					<keyname>maven</keyname>
					<passphrase>${gpg.passphrase}</passphrase>
					
					<!-- 对于较新的 GPG 版本需要此配置 -->
					<gpgArguments>
						<arg>--pinentry-mode</arg>
						<arg>loopback</arg>
					</gpgArguments>
				</configuration>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>net.nicoulaj.maven.plugins</groupId>
				<artifactId>checksum-maven-plugin</artifactId>
				<version>1.10</version>
				<executions>
					<execution>
						<id>create-checksums</id>
						<goals>
							<goal>artifacts</goal>
						</goals>
						<configuration>
							<algorithms>
								<algorithm>MD5</algorithm>
								<algorithm>SHA-1</algorithm>
							</algorithms>
							<attachChecksums>true</attachChecksums>
						</configuration>
					</execution>
					<execution>
						<id>create-pom-checksums</id>
						<goals>
							<goal>files</goal>
						</goals>
						<configuration>
							<fileSets>
								<fileSet>
									<directory>${project.build.directory}</directory>
									<includes>
										<include>*.pom</include>
									</includes>
								</fileSet>
							</fileSets>
							<algorithms>
								<algorithm>MD5</algorithm>
								<algorithm>SHA-1</algorithm>
							</algorithms>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>