<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.quiethappiness</groupId>
		<artifactId>jy-wrench</artifactId>
		<version>1.3.1-SNAPSHOT</version>
	</parent>
	
	<artifactId>jy-wrench-util-infrastructure-starter</artifactId>
	
	<name>${artifactId}</name>
	<description>jy wrench modules infrastructure util</description>
	<url>https://github.com/quiethappiness/jy-wrench</url>
	
	<licenses>
		<license>
			<name>Apache License</name>
			<url>https://opensource.org/license/apache-2-0/</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<repositories>
		<repository>
			<name>Central Portal Snapshots</name>
			<id>central-portal-snapshots</id>
			<url>https://central.sonatype.com/repository/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<developers>
		<developer>
			<id>maven</id>
			<name>jingyue</name>
			<email>zhlele2003@qq.com</email>
			<url>https://github.com/quiethappiness</url>
			<organization>jy-wrench</organization>
			<organizationUrl>https://github.com/quiethappiness/jy-wrench</organizationUrl>
			<roles>
				<role>Project Manager</role>
				<role>Developer</role>
			</roles>
			<timezone>Asia/Shanghai</timezone>
		</developer>
	</developers>
	
	<scm>
		<connection>scm:git:https://github.com/quiethappiness/jy-wrench.git</connection>
		<developerConnection>scm:git:https://github.com/quiethappiness/jy-wrench.git</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/quiethappiness/jy-wrench</url>
	</scm>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<!-- 排除 Spring Boot 默认的日志 starter -->
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<!-- <dependency> -->
		<!-- 	<groupId>org.springframework</groupId> -->
		<!-- 	<artifactId>spring-tx</artifactId> -->
		<!-- </dependency> -->
		<!-- rabbitmq -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>
			<!-- <version>3.2.0</version> -->
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
		</dependency>
		<!-- <dependency> -->
		<!-- 	<groupId>org.redisson</groupId> -->
		<!-- 	<artifactId>redisson-spring-boot-starter</artifactId> -->
		<!-- 	<scope>provided</scope> -->
		<!-- </dependency> -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<!-- okhttp -->
		<!-- http 接口框架 https://bugstack.cn/md/road-map/http.html -->
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp-sse</artifactId>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>logging-interceptor</artifactId>
		</dependency>
		<!-- jwt -->
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<!-- <scope>compile</scope> -->
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<scope>runtime</scope>
		</dependency>
		
		<!-- <dependency> -->
		<!-- 	<groupId>cn.hutool</groupId> -->
		<!-- 	<artifactId>hutool-all</artifactId> -->
		<!-- 	<version>5.8.40</version> -->
		<!-- </dependency> -->
		<dependency>
			<groupId>io.github.quiethappiness</groupId>
			<artifactId>jy-wrench-util-mq-message-starter</artifactId>
			<version>1.3.1-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
	
	</dependencies>
	
	<build>
		<finalName>${artifactId}</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
			<resource>
				<directory>src/assembly/resources</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>true</filtering>
			</testResource>
			<testResource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</testResource>
		</testResources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-archetype-plugin</artifactId>
				<version>3.2.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.5</version>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
				<version>2.18.0</version>
			</plugin>
			<!-- 			<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-resources-plugin</artifactId>
							<version>3.2.0</version>
							<configuration>
								<encoding>UTF-8</encoding>
								<resources>
									<resource>
										<directory>src/main/resources</directory>
										<filtering>false</filtering>
									</resource>
								</resources>
							</configuration>
						</plugin> -->
			
			<!--   central发布插件    -->
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
				<version>0.8.0</version>
				<extensions>true</extensions>
				<configuration>
					<publishingServerId>ossrh</publishingServerId>
					<!-- <tokenAuth>true</tokenAuth> -->
					<autoPublish>true</autoPublish>
					<waitUntil>published</waitUntil>
				</configuration>
			</plugin>
			
			<!--   source源码插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.2.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<!--   javadoc插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.9.1</version>
				<configuration>
					<charset>UTF-8</charset>
					<encoding>UTF-8</encoding>
					<docencoding>UTF-8</docencoding>
					<additionalJOption>-Xdoclint:none</additionalJOption>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<additionalparam>-Xdoclint:none</additionalparam>
							<!--  /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/bin/javadoc -->
							<javadocExecutable>
								${java.home}${file.separator}bin${file.separator}javadoc
							</javadocExecutable>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<dependencyReducedPomLocation>
								${project.build.directory}/${project.artifactId}-${project.version}.pom
							</dependencyReducedPomLocation>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<!--gpg加密-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<!--指定用于签名的 GPG 密钥名称。-->
					<keyname>maven</keyname>
					<passphrase>${gpg.passphrase}</passphrase>
					
					<!-- 对于较新的 GPG 版本需要此配置 -->
					<gpgArguments>
						<arg>--pinentry-mode</arg>
						<arg>loopback</arg>
					</gpgArguments>
				</configuration>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>net.nicoulaj.maven.plugins</groupId>
				<artifactId>checksum-maven-plugin</artifactId>
				<version>1.10</version>
				<executions>
					<execution>
						<id>create-checksums</id>
						<goals>
							<goal>artifacts</goal>
						</goals>
						<configuration>
							<algorithms>
								<algorithm>MD5</algorithm>
								<algorithm>SHA-1</algorithm>
							</algorithms>
							<attachChecksums>true</attachChecksums>
						</configuration>
					</execution>
					<execution>
						<id>create-pom-checksums</id>
						<goals>
							<goal>files</goal>
						</goals>
						<configuration>
							<fileSets>
								<fileSet>
									<directory>${project.build.directory}</directory>
									<includes>
										<include>*.pom</include>
									</includes>
								</fileSet>
							</fileSets>
							<algorithms>
								<algorithm>MD5</algorithm>
								<algorithm>SHA-1</algorithm>
							</algorithms>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>